databases:
  - name: bienestar-mysql-db
    databaseName: bienestar_db
    user: bienestar_user
    plan: free
    region: oregon
    mysqlMajorVersion: 8

services:
  - type: web
    name: bienestar-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bienestar_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bienestar_app.settings
      - key: SECRET_KEY
        value: tu_clave_secreta
      - key: DATABASE_URL
        fromDatabase:
          name: bienestar-mysql-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: bienestar-app.onrender.com
